/** Seed data — placement portal only (not DSW). */
export const MOCK_SENIORS = [
  {
    id: 'sen-aj',
    linkedInImported: true,
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha',
    name: 'Aisha Khan',
    headline: 'Software Engineer @ Google · Ex-intern',
    company: 'Google',
    role: 'Software Engineer',
    offerYear: 2025,
    placementType: 'on-campus',
    rounds: [
      { name: 'Online assessment', detail: '2 DSA, 1 ML basics' },
      { name: 'Technical phone', detail: '45 min DSA + complexity' },
      { name: 'Virtual onsite', detail: '2× DSA, 1 system design sketch' },
      { name: 'Googliness', detail: 'Behavioral, collaboration stories' },
      { name: 'Team match', detail: 'Conversations with 2 teams' },
    ],
    tips: 'Start LeetCode early; mock interviews matter. For Googleyness, prepare 6–8 STAR stories on ambiguity and teamwork.',
    resources: [
      { type: 'link', label: 'DSA patterns cheatsheet', url: 'https://example.com/dsa' },
      { type: 'pdf', label: 'My onsite notes (PDF)', url: '#' },
    ],
    linkedInUrl: 'https://www.linkedin.com/in/example',
  },
  {
    id: 'sen-rv',
    linkedInImported: true,
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul',
    name: 'Rahul Verma',
    headline: 'SDE II @ Amazon',
    company: 'Amazon',
    role: 'Software Development Engineer II',
    offerYear: 2024,
    placementType: 'on-campus',
    rounds: [
      { name: 'OA', detail: 'Debugging + reasoning' },
      { name: 'Round 1', detail: 'DSA medium-hard' },
      { name: 'Round 2', detail: 'DSA + scalable design discussion' },
      { name: 'Bar raiser', detail: 'LP deep dive' },
    ],
    tips: 'LP stories are scored rigorously — write them down and rehearse. OA debugging is easy to underestimate.',
    resources: [{ type: 'link', label: 'Leadership Principles examples', url: 'https://example.com/lp' }],
    linkedInUrl: 'https://www.linkedin.com/in/example-amz',
  },
  {
    id: 'sen-pg',
    linkedInImported: true,
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    name: 'Priya Gupta',
    headline: 'Product Analyst @ Razorpay',
    company: 'Razorpay',
    role: 'Product Analyst',
    offerYear: 2025,
    placementType: 'off-campus',
    rounds: [
      { name: 'Aptitude + SQL', detail: 'Timed SQL + MCQs' },
      { name: 'Case round', detail: 'Metric puzzles' },
      { name: 'Final', detail: 'Stakeholder-style discussion' },
    ],
    tips: 'Off-campus means you must tailor each outreach. Practice SQL window functions weekly.',
    resources: [],
    linkedInUrl: 'https://www.linkedin.com/in/example-rzp',
  },
  {
    id: 'sen-ms',
    linkedInImported: true,
    photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Meera',
    name: 'Meera Singh',
    headline: 'SWE @ Microsoft',
    company: 'Microsoft',
    role: 'Software Engineer',
    offerYear: 2023,
    placementType: 'on-campus',
    rounds: [
      { name: 'Screen', detail: 'DSA' },
      { name: 'Loop 1–3', detail: 'Mixed coding + design at scale (L4)' },
    ],
    tips: 'Microsoft interviews reward clarity — narrate your thought process. Brush up on OS basics.',
    resources: [{ type: 'link', label: 'OS notes for interviews', url: 'https://example.com/os' }],
    linkedInUrl: 'https://www.linkedin.com/in/example-msft',
  },
];
